# Data Cleaning

## Step 1: Import Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns',None)

## Step 2: Load Dataset

In [4]:
df = pd.read_csv("H:\Hospital Performance & Patient Analytics\healthcare_dataset.csv")

<>:1: SyntaxWarning: invalid escape sequence '\H'
<>:1: SyntaxWarning: invalid escape sequence '\H'
C:\Users\VIVOBBOK 16\AppData\Local\Temp\ipykernel_34192\3695177126.py:1: SyntaxWarning: invalid escape sequence '\H'
  df = pd.read_csv("H:\Hospital Performance & Patient Analytics\healthcare_dataset.csv")

## Step 3: View the Data

In [5]:
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [6]:
df.tail()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [8]:
df.sample(5)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
9231,KeVIn bOYD,20,Female,B-,Diabetes,2022-02-11,Jenny Howard,Rivera Inc,Blue Cross,31646.381805,144,Elective,2022-02-21,Aspirin,Inconclusive
5176,dENNiS rOY,51,Female,A+,Obesity,2022-04-06,Mark Buchanan,"Mata, and Gonzalez Jones",Aetna,32178.964795,325,Urgent,2022-04-29,Aspirin,Normal
22723,caLVIN bURnEtT,51,Male,B-,Diabetes,2022-03-05,Brian Harvey,Hall-Fritz,Aetna,21604.873290,183,Elective,2022-03-14,Ibuprofen,Inconclusive
24432,vaNessA MasON,80,Male,A-,Diabetes,2023-11-03,Michael Lucas,"and Levy Patterson, Farley",Blue Cross,46398.590023,487,Elective,2023-11-28,Paracetamol,Inconclusive
21013,sumMer RICHARDsoN,84,Male,A+,Cancer,2021-07-17,Jesse Newman,Ltd Palmer,Medicare,37664.423306,475,Urgent,2021-07-23,Ibuprofen,Inconclusive

## Step 4: Dataset Shape

In [9]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 55500
Columns : 15

## Step 5: Column Information

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

## Step 6: Statistical Summary

In [11]:
df.describe()

                Age  Billing Amount   Room Number
count  55500.000000    55500.000000  55500.000000
mean      51.539459    25539.316097    301.134829
std       19.602454    14211.454431    115.243069
min       13.000000    -2008.492140    101.000000
25%       35.000000    13241.224652    202.000000
50%       52.000000    25538.069376    302.000000
75%       68.000000    37820.508436    401.000000
max       89.000000    52764.276736    500.000000

## Step 7: Missing Values

In [12]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

## Step 8: Duplicate Records

In [13]:
df.duplicated().sum()

np.int64(534)

In [14]:
df.drop_duplicates(inplace=True)

In [15]:
df.duplicated().sum()

np.int64(0)

## Step 9: Convert Date Columns

In [16]:
df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])
df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 54966 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                54966 non-null  object
 1   Age                 54966 non-null  int64
 2   Gender              54966 non-null  object
 3   Blood Type          54966 non-null  object
 4   Medical Condition   54966 non-null  object
 5   Date of Admission   54966 non-null  datetime64[ns]
 6   Doctor              54966 non-null  object
 7   Hospital            54966 non-null  object
 8   Insurance Provider  54966 non-null  object
 9   Billing Amount      54966 non-null  float64
 10  Room Number         54966 non-null  int64
 11  Admission Type      54966 non-null  object
 12  Discharge Date      54966 non-null  datetime64[ns]
 13  Medication          54966 non-null  object
 14  Test Results        54966 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(2), object(10)
memory usage: 6.7+ MB

## Step 10: Create Length of Stay

In [18]:
df["Length of Stay"] = (
    df["Discharge Date"] -
    df["Date of Admission"]
).dt.days

## Step 11: Create Age Group

In [19]:
bins = [0,18,35,50,65,100]

labels = [
    "0-18",
    "19-35",
    "36-50",
    "51-65",
    "65+"
]

df["Age Group"] = pd.cut(
    df["Age"],
    bins=bins,
    labels=labels
)

## Step 12: Extract Date Features

In [21]:
df["Year"] = df["Date of Admission"].dt.year

df["Month"] = df["Date of Admission"].dt.month_name()

df["Quarter"] = df["Date of Admission"].dt.quarter

## Step 13: Check Data Types Again

In [22]:
df.dtypes

Name                          object
Age                            int64
Gender                        object
Blood Type                    object
Medical Condition             object
Date of Admission     datetime64[ns]
Doctor                        object
Hospital                      object
Insurance Provider            object
Billing Amount               float64
Room Number                    int64
Admission Type                object
Discharge Date        datetime64[ns]
Medication                    object
Test Results                  object
Length of Stay                 int64
Age Group                   category
Year                           int32
Month                         object
Quarter                        int32
dtype: object

## Step 14: Save Clean Dataset

In [24]:
df.to_csv(
    "clean_healthcare_dataset.csv",
    index=False
)
print("Data is saved")

Data is saved